### PR TITLE
Fixes issue 1664. SwitchNetwork exposes API keys when adding a new network

### PR DESCRIPTION
**Pull request by nfts2me**
## Description

Check https://github.com/wagmi-dev/wagmi/issues/1664

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:
nfts2me.eth

### CODE REVIEW

**Comment by jxom** [comment]
Removing the override in the alchemy, infura & jsonRpc providers will: 

1. break some connectors that rely on `.default` (e.g. `WalletConnectConnector`), and 
2. make this a breaking change.

Instead, how about we append a `public` key when we override the `default` RPC URL, that the `addEthereumChain` method relys on? Example:

`packages/core/src/providers/alchemy.ts`
```diff
chain: {
  ...chain,
  rpcUrls: {
    ...chain.rpcUrls,
+   public: chains.rpcUrls.default,
    default: { http: [`${chain.rpcUrls.alchemy?.http[0]}/${apiKey}`] },
  },
},
```

`references/packages/connectors/src/injected.ts`
```diff
await provider.request({
  method: 'wallet_addEthereumChain',
  params: [
    {
      chainId: id,
      chainName: chain.name,
      nativeCurrency: chain.nativeCurrency,
      rpcUrls: [
        chain.rpcUrls.public?.http[0] ??
-         chain.rpcUrls.default.http[0] ??
          '',
      ],
      blockExplorerUrls: this.getBlockExplorerUrls(chain),
    },
  ],
})
```

**Comment by nfts2me** [comment]
Done.
Also updated for packages/connectors/src/coinbaseWallet.ts that exposed it as well.

**Comment by jxom** [comment]
Hey @nfts2me, thanks so much for the PR!

After thinking about this again, and chatting with @tmm. I think it might be better to include the `public` attribute on the RPC URLs of the chains in [wagmi-dev/references](https://github.com/wagmi-dev/references), to deterministically identify a chain's "public" RPC URL.

Do you think you could make these changes? Otherwise, I can cover this for you. 

Quick overview:

1. Close this PR here (as there will be no direct changes in the wagmi repo),
2. Keep your changes in the `references/` submodule, but also add a `rpcUrls.public` attribute to the chains with the public RPC URL,
3. Raise a PR in the [wagmi-dev/references](https://github.com/wagmi-dev/references) repository.

**Comment by nfts2me** [comment]
Makes sense.
I've added the PR.

Also changed the types.ts to add the new public as part of rpcUrls

**Pull request closed without merging**
