### PR TITLE
Add string type to argument of fetchEnsAvatar to allow for name entry

### PR DESCRIPTION
**Pull request by lucemans**
## Description

Add `string` type to `fetchEnsAvatar` to match the comment "or ENS name"

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md)

Your ENS/address: luc.computer

### CODE REVIEW

**Comment by tmm** [comment]
Hey! If you want to fetch the ENS avatar by ENS name, you should compose the [`fetchEnsAddress`](https://wagmi.sh/core/actions/fetchEnsAddress) action:

```
import { fetchEnsAddress, fetchEnsAvatar } from '@wagmi/core'
 
const address = await fetchEnsAddress({ name: 'awkweb.eth' })
const avatar = await fetchEnsAvatar({ address })
```

**Comment by robiot** [comment]
image
It does say "address or ens name" in the doc comment, and it works with ens-names. So the type is not correct.

**Comment by lucemans** [comment]
In the comments on line 6 it says "or ENS name"

**Comment by lucemans** [comment]
@tmm Could you have another look at this?

**Comment by tmm** [comment]
We should remove ` or ENS name` then. LMK if you want to do it (for the credit). Otherwise, I can.

**Pull request closed without merging**
