### PR TITLE
feat(solid): Implement solid playground and core hooks

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description

- Added a new package called `@wagmi/solid` containing reactivity for solid and some account hooks
- Added a new playground using solid base starter in order to test solid hooks
- Added tests for the core hooks

⚠️ We encountered an error while using solid start, not happening when using the default solid starter:

`TypeError: Class extends value undefined is not a constructor or null at /references/packages/connectors/src/base.ts24:10`

After investigating, it looks like `EventEmitter` from `connectors/base.ts` is undefined while using SSR with solid-start on the nodejs side, we actually can't figure out why it's working with next for the moment but not with solid start, so we did switch to the regular solid starter using vite 4 and it works perfectly

@gabrieldemian 

## Current core hooks implemented

- [x] useAccount
- [x] useConnect
- [x] useContract
- [x] useDisconnect
- [x] useNetwork
- [x] useProvider
- [x] useSigner
- [x] useSwitchNetwork
- [x] useWebSocketProvider

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:
0xm4king.eth / 0xfd42860cD619FE2060712DC5833F0B039b23e00a

### CODE REVIEW

**Comment by NeOMakinG** [comment]
@jxom @tmm Feel free to do a first review pass if you want, most of the hooks are working and tested, we did some dirty workaround on tests because `@tanstack/solid-query` mutations are not working as expected, we might need to contribute to it asap

**Comment by roninjin10** [comment]
Exciting!

**Comment by gabrieldemian** [comment]
> Exciting!

Thank you! Feel free to contribute if you want. I'm waiting for Tanstack to fix some bugs on their Solid adaptor to continue working on this PR.

**Comment by gabrieldemian** [comment]
Guys, I did a lot of progress and I think this PR is ready. A summary of what I did:
- Updated tanstack query to v5 alpha
- Wrote documentation for the hooks
- Fixed unit tests
- Fixed broken reactivity of mutations

@NeOMakinG can you just change the target branch to `main`?
@tmm

**Pull request closed without merging**
