### PR TITLE
v1

### PR DESCRIPTION
**Pull request by jxom**
Release Candidate for v1. Check out the [Migration Guide](https://next.wagmi.sh/react/migration-guide).

**Release date:** Between **2023-05-05** and **2023-05-12**.
**NPM:** `npm i wagmi@next viem`
**Discussion:** #2207 

### Docs

- [wagmi v1 Docs](https://next.wagmi.sh)
- [wagmi v1 Migration Guide](https://next.wagmi.sh/react/migration-guide)
- [viem Docs](https://viem.sh)
- [ethers.js → viem Migration Guide](https://viem.sh/docs/ethers-migration.html)

### Examples

- wagmi v1 example: [Repo](https://github.com/jxom/wagmi-v1-example) – [Demo](https://wagmi-v1-example.vercel.app/)

### Third-Party Tooling

- RainbowKit PR: https://github.com/rainbow-me/rainbowkit/pull/1188
- ConnectKit PR: https://github.com/family/connectkit/pull/209

---

### Code

- [x] `@wagmi/core` 
  - [x] Actions
  - [x] Types
  - [x] Utilities
  - [x] Migrate `configureChains` 
  - [x] Remove redundant modules
  - [x] Rename "Provider" & "Signer" terminology to "Public Client" & "Wallet Client"
- [x] `wagmi` 
  - [x] Hooks
  - [x] Utilities
  - [x] Remove redundant modules
  - [x] Rename "Provider" & "Signer" terminology to "Public Client" & "Wallet Client"
- [x] [`@wagmi/connectors`](https://github.com/wagmi-dev/references/pull/215)
- [x] CLI (React)

### Docs

- [x] Update Examples
- [x] `core/chains.en-US.mdx`
- [x] `core/client.en-US.mdx`
- [x] `core/getting-started.en-US.mdx`
- [x] `core/actions/connect.en-US.mdx`
- [x] `core/actions/disconnect.en-US.mdx`
- [x] `core/actions/fetchBalance.en-US.mdx`
- [x] `core/actions/fetchBlockNumber.en-US.mdx`
- [x] `core/actions/fetchEnsAddress.en-US.mdx`
- [x] `core/actions/fetchEnsAvatar.en-US.mdx`
- [x] `core/actions/fetchEnsName.en-US.mdx`
- [x] `core/actions/fetchEnsResolver.en-US.mdx`
- [x] `core/actions/fetchFeeData.en-US.mdx`
- [x] `core/actions/fetchSigner.en-US.mdx`
- [x] `core/actions/fetchToken.en-US.mdx`
- [x] `core/actions/fetchTransaction.en-US.mdx`
- [x] `core/actions/getAccount.en-US.mdx`
- [x] `core/actions/getContract.en-US.mdx`
- [x] `core/actions/getNetwork.en-US.mdx`
- [x] `core/actions/getProvider.en-US.mdx`
- [x] `core/actions/getWebSocketProvider.en-US.mdx`
- [x] `core/actions/multicall.en-US.mdx`
- [x] `core/actions/prepareSendTransaction.en-US.mdx`
- [x] `core/actions/prepareWriteTransaction.en-US.mdx`
- [x] `core/actions/readContract.en-US.mdx`
- [x] `core/actions/readContracts.en-US.mdx`
- [x] `core/actions/sendTransaction.en-US.mdx`
- [x] `core/actions/signMessage.en-US.mdx`
- [x] `core/actions/signTypedData.en-US.mdx`
- [x] `core/actions/switchNetwork.en-US.mdx`
- [x] `core/actions/waitForTransaction.en-US.mdx`
- [x] `core/actions/watchAccount.en-US.mdx`
- [x] `core/actions/watchBlockNumber.en-US.mdx`
- [x] `core/actions/watchContractEvent.en-US.mdx`
- [x] `core/actions/watchMulticall.en-US.mdx`
- [x] `core/actions/watchNetwork.en-US.mdx`
- [x] `core/actions/watchPendingTransactions.en-US.mdx`
- [x] `core/actions/watchProvider.en-US.mdx`
- [x] `core/actions/watchReadContract.en-US.mdx`
- [x] `core/actions/watchReadContracts.en-US.mdx`
- [x] `core/actions/watchSigner.en-US.mdx`
- [x] `core/actions/watchWebSocketProvider.en-US.mdx`
- [x] `core/actions/writeContract.en-US.mdx`
- [x] `core/connectors/coinbaseWallet.en-US.mdx`
- [x] `core/connectors/injected.en-US.mdx`
- [x] `core/connectors/ledger.en-US.mdx`
- [x] `core/connectors/metaMask.en-US.mdx`
- [x] `core/connectors/mock.en-US.mdx`
- [x] `core/connectors/safe.en-US.mdx`
- [x] `core/connectors/walletConnect.en-US.mdx`
- [x] `core/connectors/walletConnectLegacy.en-US.mdx`
- [x] `core/providers/alchemy.en-US.mdx`
- [x] `core/providers/configuring-chains.en-US.mdx`
- [x] `core/providers/infura.en-US.mdx`
- [x] `core/providers/jsonRpc.en-US.mdx`
- [x] `core/providers/public.en-US.mdx`
- [x] `react/actions.en-US.mdx`
- [x] `react/chains.en-US.mdx`
- [x] `react/comparison.en-US.mdx`
- [x] `react/getting-started.en-US.mdx`
- [x] `react/prepare-hooks.en-US.mdx`
- [x] `react/WagmiConfig.en-US.mdx`
- [x] `react/connectors/coinbaseWallet.en-US.mdx`
- [x] `react/connectors/injected.en-US.mdx`
- [x] `react/connectors/ledger.en-US.mdx`
- [x] `react/connectors/metaMask.en-US.mdx`
- [x] `react/connectors/mock.en-US.mdx`
- [x] `react/connectors/safe.en-US.mdx`
- [x] `react/connectors/walletConnect.en-US.mdx`
- [x] `react/connectors/walletConnectLegacy.en-US.mdx`
- [x] `react/hooks/useAccount.en-US.mdx`
- [x] `react/hooks/useBalance.en-US.mdx`
- [x] `react/hooks/useBlockNumber.en-US.mdx`
- [x] `react/hooks/useConnect.en-US.mdx`
- [x] `react/hooks/useContract.en-US.mdx`
- [x] `react/hooks/useContractEvent.en-US.mdx`
- [x] `react/hooks/useContractInfiniteReads.en-US.mdx`
- [x] `react/hooks/useContractRead.en-US.mdx`
- [x] `react/hooks/useContractReads.en-US.mdx`
- [x] `react/hooks/useContractWrite.en-US.mdx`
- [x] `react/hooks/useDisconnect.en-US.mdx`
- [x] `react/hooks/useEnsAvatar.en-US.mdx`
- [x] `react/hooks/useEnsAddress.en-US.mdx`
- [x] `react/hooks/useEnsResolver.en-US.mdx`
- [x] `react/hooks/useFeeData.en-US.mdx`
- [x] `react/hooks/useNetwork.en-US.mdx`
- [x] `react/hooks/useProvider.en-US.mdx`
- [x] `react/hooks/useSendTransaction.en-US.mdx`
- [x] `react/hooks/useSignMessage.en-US.mdx`
- [x] `react/hooks/useSignTypedData.en-US.mdx`
- [x] `react/hooks/useSwitchNetwork.en-US.mdx`
- [x] `react/hooks/useToken.en-US.mdx`
- [x] `react/hooks/useTransaction.en-US.mdx`
- [x] `react/hooks/useWaitForTransaction.en-US.mdx`
- [x] `react/hooks/useWatchPendingTransactions.en-US.mdx`
- [x] `react/hooks/useWebSocketProvider.en-US.mdx`
- [x] `react/prepare-hooks/usePrepareContractWrite.en-US.mdx`
- [x] `react/prepare-hooks/usePrepareSendTransaction.en-US.mdx`
- [x] `react/providers/alchemy.en-US.mdx`
- [x] `react/providers/configuring-chains.en-US.mdx`
- [x] `react/providers/infura.en-US.mdx`
- [x] `react/providers/jsonRpc.en-US.mdx`
- [x] `react/providers/public.en-US.mdx`

### Migration Guide

- [x] General
  - [x] Migrated from Ethers.js to viem.
  - [x] `BigNumber` has been removed in favor of browser-native `BigInt`.
    - [x] Note that `BigInt` is not serializable (use `serialize`/`deserialize`).
  - [x] `gasLimit` is now `gas`.
  - [x] Ethers v5 "Provider" & "Signer" terminology is now known as viem's "Public Client" & "Wallet Client" terminology.
  - [x] Removed global type declaration for `window.ethereum`.
  - [x] Renamed `Ethereum` type to `WindowProvider`.
- [x] Actions/Hooks
  - [x] `connect`/`useConnect` @tmm
  - [x] `fetchBalance` / `useBalance` @tmm
  - [x] `fetchBlockNumber` / `useBlockNumber` @tmm
  - [x] `fetchEnsAvatar` / `useEnsAvatar` @tmm
  - [x] `fetchFeeData` / `useFeeData` @tmm
  - [x] `fetchSigner` / `useSigner` / `watchSigner` @tmm
  - [x] `fetchToken` / `useToken` @tmm
  - [x] `fetchTransaction` / `useTransaction` @tmm
  - [x] `useContract` / `getContract` @tmm
  - [x] `getProvider` / `useProvider` / `watchProvider` @tmm
  - [x] `getWebSocketProvider` / `useWebSocketProvider` / `watchWebSocketProvider` @tmm
  - [x] `multicall`
  - [x] `prepareSendTransaction` / `usePrepareSendTransaction`
  - [x] `prepareWriteContract` / `usePrepareContractWrite`
  - [x] `readContract` / `useContractRead`
  - [x] `readContracts` / `useContractReads` / `useContractInfiniteReads`
  - [x] `signMessage` / `useSignMessage`
  - [x] `signTypedData` / `useSignTypedData`
  - [x] `waitForTransaction`/`useWaitForTransaction`
  - [x] `watchPendingTransactions` / `useWatchPendingTransactions`
  - [x] `writeContract` / `useContractWrite`
  - [x] `watchContractEvent` / `useContractEvent`
- [x] `configureChains`
- [x] Connectors
  - [x] `getSigner` now returns a viem [`WalletClient`](https://viem.sh/docs/clients/wallet.html) instead of an Ethers `Signer`.
  - [x] Removed `Signer` generic.
- [x] Errors
  - [x] Removed `ChainDoesNotSupportMulticallError`, `ContractMethodDoesNotExistError`, `ContractMethodNoResultError`, `ContractMethodRevertedError`, `ContractResultDecodeError`, `ProviderRpcError`, `ResourceUnavailableError`

### Build

- [x] Resolve `pnpm build` issues

### CODE REVIEW

**Comment by firnprotocol** [comment]
can you clarify the nomenclature "next" in the version name? does this intend to convey that we should be using next with the project, or unrelated? thanks.

**Comment by QuintonC** [comment]
> can I ask about the nomenclature "next" in the version name? does this intend to convey that we should be using Next.js with the project, or unrelated? thanks.

`next` is a tag that can be used to offer a different stream of development for developers. It allows folks to test the package in different environments.

npm has [documentation on tags](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag) if you're wanting to learn more about how they work and what their purpose is. 

Hope that answers your question :)

**Comment by QuintonC** [comment]
> can I ask about the nomenclature "next" in the version name? does this intend to convey that we should be using Next.js with the project, or unrelated? thanks.

@firnprotocol `next` is a tag that can be used to offer a different stream of development for developers. It allows folks to test the package in different environments.

npm has [documentation on tags](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag) if you're wanting to learn more about how they work and what their purpose is. 

Hope that answers your question :)

**Comment by bigint** [comment]
Guys seems like you left docs for `useWalletClient` 🙇🏼 

https://next.wagmi.sh/react/hooks/useWalletClient

**Pull request merged**
