### PR TITLE
Translation kick off: Simplified Chinese

### PR DESCRIPTION
**Pull request by noyyyy**
**Note**: Translation Progress discussion: https://github.com/wagmi-dev/wagmi/discussions/1582

## Description

Start the translation of Simplified Chinese with configuration and two mdx.

There is a discussion before https://github.com/wagmi-dev/wagmi/discussions/1461.

Translation would be long progress and will be fulfilled with many pr. So, I'd like to create a discussion to record the translation progress and people can translate it one page by one page.

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address: 0x7E480e349a31F71f59B57cb30Bd850b4D643D617

### CODE REVIEW

**Comment by tmm** [comment]
Excited for this! I can send a tweet out to the community next week to see if there is anyone else interested in helping with this.

**Comment by noyyyy** [comment]
Do I need to make some commits to make the test pass? Also, I make a draft translation progress record in discussion https://github.com/wagmi-dev/wagmi/discussions/1582

**Comment by tmm** [comment]
I wouldn't worry about the tests. I think you need to add a `ANVIL_FORK_URL` environment variable to your fork to get it to run correctly.

Let's link the discussion thread to the PR description so folks can discover it more easily.

**Comment by noyyyy** [comment]
I think this pr is ready to be merged if there are no other problems, and translation by page can start. I would send a tweet about this and create a telegram group for communication besides translation.

Btw, I config `ANVIL_FORK_URL` in my forked repo but it fail to pass the test due to dependencies install error. The main repo has no such problem as it uses the cache. I try to run the test locally and some tests still fail. Hope CI can work.

**Comment by noyyyy** [comment]
Just pull some commits from upstream and the test passes this time in my repo.  https://github.com/noyyyy/wagmi/actions/runs/3839220790
Can not wait to see its merge!

**Comment by noyyyy** [comment]
Hi @tmm, how do we move forward next?

**Comment by tmm** [comment]
@noyyyy merging in! I hid all untranslated pages so as they are translated, you can unhide them by removing `"display": "hidden"` from `_meta.zh-CN.json`.

**Comment by noyyyy** [comment]
> @noyyyy merging in! I hid all untranslated pages so as they are translated, you can unhide them by removing `"display": "hidden"` from `_meta.zh-CN.json`.

Get it. Will continue translating with community.

**Comment by tmm** [comment]
Sounds great! Feel free to @ mention me in any PRs or discussion if I can be helpful. 谢谢

**Pull request merged**
