### PR TITLE
docs(cn): translate /docs/pages/react/typescript.en-US.mdx into Chinese

### PR DESCRIPTION
**Pull request by byteHulk**
## Description

Translate a single chapter. typescript

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address: 0x1d1FA8910d665Fb1989E3caE1FA6160915734C17

### CODE REVIEW

**Comment by byteHulk** [comment]
In addition, is it possible to display a document without Chinese translation as an English document, it should not be 404

**Comment by tmm** [comment]
Thanks for adding this in!

> In addition, is it possible to display a document without Chinese translation as an English document, it should not be 404

Will think about this some more!

**Comment by byteHulk** [comment]
@tmm  lint error. What I can do to help with the merge?

**Comment by byteHulk** [comment]
@jxom

**Comment by tmm** [comment]
Thanks for contributing! Sorry it took so long to get this merged in.

**Pull request merged**
