### PR TITLE
Add support for BNB Smart Chain

### PR DESCRIPTION
**Pull request by taycaldwell**
## Description

Add support for:

- BNB Smart Chain
- BNB Smart Chain Testnet

https://github.com/wagmi-dev/wagmi/discussions/914

## Additional Information

- [X] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:

taycaldwell.eth

### CODE REVIEW

**Comment by taycaldwell** [comment]
As requested in discussion https://github.com/wagmi-dev/wagmi/discussions/914

**Comment by armatrix** [comment]
update plz

**Comment by TIM88-DOT** [comment]
+1

**Comment by jxom** [comment]
Thanks for the PR. With the introduction of `0.9.x`, wagmi now comes with the `bnb` & `bnbTestnet` chains built-in (re-exported from our [`@wagmi/chains` reference repository](https://github.com/wagmi-dev/references/tree/main/packages/chains)). Read more [here](https://wagmi.sh/react/chains).

Really sorry for the hassle – we really appreciate this PR.

**Comment by taycaldwell** [comment]
No problem. Thank you for adding support!

**Pull request closed without merging**
