### PR TITLE
fix: the ordering of the contractMap key

### LINKED ISSUE #2528: bug: `wagmi generate` with foundry plugin shuffles output, producing large diffs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.0

### Current Behavior

Running `wagmi generate` outputs contracts in seemingly random order each time it's run.

### Expected Behavior

**Running `wagmi generate` twice on identical inputs should, ideally, generate identical outputs.**

This has two main benefits:
- Concise git diff
- Reproducible builds

### Steps To Reproduce

To reproduce easily

```
git clone https://github.com/daimo-eth/daimo
cd daimo/packages/daimo-api
git checkout 603a172e
npm ci && npm run gen
```

This runs `wagmi generate`. Finally, run

```
git diff
```

**This shows a big diff.** The input contracts have not changed. Output`gen/contracts.ts` is functionally identical but reordered.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/daimo-eth/daimo/tree/603a172eb9f902b11446f8d0721956cb338cd47a

### Anything else?

**This might be fixable by sorting the ABI items by name, internally, before generating output.**

Finally, I recommend removing the date from the header line
```
// Generated by @wagmi/cli@1.1.0 on 6/10/2023 at 4:33:44 AM
```

at which point identical inputs = identical generated outputs.

### PR DESCRIPTION
**Pull request by Iamshankhadeep**
## Description

fix #2528 

Your ENS/address:
0x5B0b82ECf7C4dA9906690023C1714Bf667EfaB32

### CODE REVIEW

**Comment by Iamshankhadeep** [comment]
@tmm I think this should fix the issue,

**Comment by dcposch** [comment]
cc @tmm , I think the test failure might be a false positive?

Let me know if I can help. Would love to get deterministic build with `wagmi cli`.

**Comment by Iamshankhadeep** [comment]
@tmm can you let me know why the test is failing so that I can update the required file to fix test.

**Comment by llllvvuu** [comment]
Looks like a false positive to me too, maybe can rebase to latest `main` to trigger a re-run

**Comment by Iamshankhadeep** [comment]
Just rebased on top of main, need to wait for authorization once again. @tmm

**Comment by dcposch** [comment]
cc @jxom 

this small changes fixes a significant issue for us. i think this affects many projects who are using wagmi cli seriously.

we need traceability in the sense that:
- auditors review contracts
- we rerun `wagmi generate` and verify no diff , so we know bindings match

currently that second step *always* generates a big diff due to random order

this small PR fixes that.

**Comment by tmm** [comment]
Thanks for working on this and appreciate the patience!

**Pull request merged**
