### PR TITLE
feat(solid): Implement solid playground and core hooks

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description

- Added a new package called `@wagmi/solid` containing reactivity for solid and some account hooks
- Added a new playground using solid base starter in order to test solid hooks
- Added tests for the core hooks

⚠️ We encountered an error while using solid start, not happening when using the default solid starter:

`TypeError: Class extends value undefined is not a constructor or null at /references/packages/connectors/src/base.ts24:10`

After investigating, it looks like `EventEmitter` from `connectors/base.ts` is undefined while using SSR with solid-start on the nodejs side, we actually can't figure out why it's working with next for the moment but not with solid start, so we did switch to the regular solid starter using vite 4 and it works perfectly

@gabrieldemian 

## Current core hooks implemented

- [x] useAccount
- [x] useConnect
- [x] useContract
- [x] useDisconnect
- [x] useNetwork
- [x] useProvider
- [x] useSigner
- [x] useSwitchNetwork
- [x] useWebSocketProvider

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:
0xm4king.eth / 0xfd42860cD619FE2060712DC5833F0B039b23e00a

### CODE REVIEW

**Comment by NeOMakinG** [comment]
@gabrieldemian I had to open a new PR because we can't change the base branch

**Comment by NeOMakinG** [comment]
@tmm for references: https://github.com/wagmi-dev/wagmi/pull/1677#issuecomment-1454354545

**Comment by tmm** [comment]
Thanks for pushing this along everyone! Going to mark as a draft for now.

Once `wagmi@1` is out (switching from ethers to [viem](https://viem.sh/) and a few other nice updates), will make sure this gets a proper review and release.

**Comment by NeOMakinG** [comment]
> Thanks for pushing this along everyone! Going to mark as a draft for now.
> 
> 
> 
> Once `wagmi@1` is out (switching from ethers to [viem](https://viem.sh/) and a few other nice updates), will make sure this gets a proper review and release.

Nice to get some news there, keep us in touch, can't wait ✌️

**Comment by NeOMakinG** [comment]
@tmm Are we ready to rebase, fix and review this?

**Comment by tmm** [comment]
Appreciate you all working on this! There are some updates on the [`alpha`](https://github.com/wagmi-dev/wagmi/tree/alpha) branch that will make adding additional framework adapters much easier. Once the next major version of Wagmi is released, we can work on getting this in.

**Comment by glitch-txs** [comment]
any updates on this? 👀

**Comment by glitch-txs** [comment]
can we re-open an draft it? @tmm

**Pull request closed without merging**
